// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using travel_recommendation_and_booking_system.Data;

#nullable disable

namespace travelrecommendationandbookingsystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611153215_AddChucVuPhongBanToNguoiDung")]
    partial class AddChucVuPhongBanToNguoiDung
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.Banner", b =>
                {
                    b.Property<int>("MaBanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBanner"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LinkLienKet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaBanner");

                    b.ToTable("Banner");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.CLoaiHinhTour", b =>
                {
                    b.Property<int>("MaLoaiTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiTour"));

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLoaiTour")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLoaiTour");

                    b.ToTable("LoaiHinhTour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.CTLichTrinh", b =>
                {
                    b.Property<int>("MaCTLT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTLT"));

                    b.Property<DateTime>("GioBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GioKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoatDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDiaDiem")
                        .HasColumnType("int");

                    b.Property<int>("MaLichTrinh")
                        .HasColumnType("int");

                    b.HasKey("MaCTLT");

                    b.HasIndex("MaDiaDiem");

                    b.HasIndex("MaLichTrinh");

                    b.ToTable("CTLichTrinh");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.ChuyenKhoiHanh", b =>
                {
                    b.Property<int>("MaChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuyen"));

                    b.Property<string>("DiemDen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiemKhoiHanh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GioDenNoiDi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GioDenNoiVe")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaChuyenCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaHDV")
                        .HasColumnType("int");

                    b.Property<int>("MaPhuongTien")
                        .HasColumnType("int");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKhoiHanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongCho")
                        .HasColumnType("int");

                    b.Property<string>("TenChuyen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaChuyen");

                    b.HasIndex("MaHDV");

                    b.HasIndex("MaPhuongTien");

                    b.HasIndex("MaTour");

                    b.ToTable("ChuyenKhoiHanh");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("DiemDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTour");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DanhSachYeuThich", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("TourMaTour")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung", "MaTour");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.HasIndex("TourMaTour");

                    b.ToTable("DanhSachYeuThich");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DiaDiem", b =>
                {
                    b.Property<int>("MaDiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiaDiem"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("KhuVuc")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiDiaDiem")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuocGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TinhThanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDiaDiem");

                    b.ToTable("DiaDiem");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DonDatTour", b =>
                {
                    b.Property<int>("MaDonDatTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonDatTour"));

                    b.Property<int>("MaChuyen")
                        .HasColumnType("int");

                    b.Property<string>("MaDatCho")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaKhachSan")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaUuDai")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoEmBe")
                        .HasColumnType("int");

                    b.Property<int>("SoNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SoTreEm")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThaiThanhToan")
                        .HasColumnType("bit");

                    b.HasKey("MaDonDatTour");

                    b.HasIndex("MaChuyen");

                    b.HasIndex("MaKhachSan");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaUuDai");

                    b.ToTable("DonDatTour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.GiaChuyen", b =>
                {
                    b.Property<int>("MaGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGia"));

                    b.Property<decimal>("GiaEmBe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaNguoiLon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTreEm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HangKhachSan")
                        .HasColumnType("int");

                    b.Property<int>("Machuyen")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhuThuPhongDon")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaGia");

                    b.HasIndex("Machuyen");

                    b.ToTable("GiaChuyen");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.HinhAnhSK", b =>
                {
                    b.Property<int>("MaAnhSK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnhSK"));

                    b.Property<bool>("AnhChinh")
                        .HasColumnType("bit");

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaKhachSan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaAnhSK");

                    b.HasIndex("MaKhachSan");

                    b.ToTable("HinhAnhSK");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.HinhAnhTour", b =>
                {
                    b.Property<int>("MaAnhTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnhTour"));

                    b.Property<bool>("AnhChinh")
                        .HasColumnType("bit");

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaAnhTour");

                    b.HasIndex("MaTour");

                    b.ToTable("HinhAnhTour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.KS_TN", b =>
                {
                    b.Property<int>("MaKhachSan")
                        .HasColumnType("int");

                    b.Property<int>("MaTienNghi")
                        .HasColumnType("int");

                    b.Property<int>("KhachSanMaKhachSan")
                        .HasColumnType("int");

                    b.Property<int>("TienNghiMaTienNghi")
                        .HasColumnType("int");

                    b.HasKey("MaKhachSan", "MaTienNghi");

                    b.HasIndex("KhachSanMaKhachSan");

                    b.HasIndex("TienNghiMaTienNghi");

                    b.ToTable("KS_TN");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasMaxLength(100)
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LoaiKhach")
                        .HasColumnType("int");

                    b.Property<int>("MaDonDatTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaDonDatTour");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.KhachSan", b =>
                {
                    b.Property<int>("MaKhachSan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachSan"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.Property<string>("TenKhachSan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaKhachSan");

                    b.ToTable("KhachSan");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.LichTrinh", b =>
                {
                    b.Property<int>("MaLichTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichTrinh"));

                    b.Property<string>("BuaAn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoatDongChinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LuuY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoThuTuNgay")
                        .HasColumnType("int");

                    b.Property<string>("TenLichTrinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLichTrinh");

                    b.HasIndex("MaTour");

                    b.ToTable("LichTrinh");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.LienHe", b =>
                {
                    b.Property<int>("MaLienHe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLienHe"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLienHe");

                    b.ToTable("LienHe");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.Newsletter", b =>
                {
                    b.Property<int>("MaNewsletter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNewsletter"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNewsletter");

                    b.ToTable("Newsletter");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<int?>("ChucVu")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DuongDanAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhongBan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ThoiGianHetHanOtp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NguoiDung");

                    b.HasData(
                        new
                        {
                            MaNguoiDung = 1,
                            Email = "admin@gmail.com",
                            HoTen = "Quản Trị Viên",
                            MaVaiTro = 1,
                            MatKhau = "$2a$11$NY4RZvWM9RFaGDoAFgOqGe62YSijcw579fDBBjQfAb49TfmcdKhFu",
                            NgayCapNhat = new DateTime(2026, 6, 11, 22, 32, 15, 284, DateTimeKind.Local).AddTicks(515),
                            NgayTao = new DateTime(2026, 6, 11, 22, 32, 15, 284, DateTimeKind.Local).AddTicks(500),
                            SoDienThoai = "0988888888",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.PhienDangNhap", b =>
                {
                    b.Property<int>("MaPhien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhien"));

                    b.Property<string>("DiaChiIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhien");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("PhienDangNhaps");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.PhuongTien", b =>
                {
                    b.Property<int>("MaPhuongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuongTien"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenPhuongTien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaPhuongTien");

                    b.ToTable("PhuongTien");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.SoThichNguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiTour")
                        .HasColumnType("int");

                    b.Property<float>("DiemYeuThich")
                        .HasColumnType("real");

                    b.Property<int>("LoaiHinhTourMaLoaiTour")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung", "MaLoaiTour");

                    b.HasIndex("LoaiHinhTourMaLoaiTour");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("SoThichNguoiDung");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<int>("MaDonDatTour")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhuongThucThanhToan")
                        .HasColumnType("bit");

                    b.Property<bool>("TrangThaiThanhToan")
                        .HasColumnType("bit");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDonDatTour");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.ThongTinTrang", b =>
                {
                    b.Property<int>("MaTTTrang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTTTrang"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Noidung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("MaTTTrang");

                    b.ToTable("ThongTinTrang");

                    b.HasData(
                        new
                        {
                            MaTTTrang = 1,
                            Key = "logo_url",
                            NgayCapNhat = new DateTime(2026, 6, 11, 22, 32, 15, 284, DateTimeKind.Local).AddTicks(1001),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 2,
                            Key = "ten_trang",
                            NgayCapNhat = new DateTime(2026, 6, 11, 22, 32, 15, 284, DateTimeKind.Local).AddTicks(1007),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 3,
                            Key = "facebook_url",
                            NgayCapNhat = new DateTime(2026, 6, 11, 22, 32, 15, 284, DateTimeKind.Local).AddTicks(1008),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 4,
                            Key = "dia_chi",
                            NgayCapNhat = new DateTime(2026, 6, 11, 22, 32, 15, 284, DateTimeKind.Local).AddTicks(1009),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 5,
                            Key = "so_dien_thoai",
                            NgayCapNhat = new DateTime(2026, 6, 11, 22, 32, 15, 284, DateTimeKind.Local).AddTicks(1009),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 6,
                            Key = "footer_copyright",
                            NgayCapNhat = new DateTime(2026, 6, 11, 22, 32, 15, 284, DateTimeKind.Local).AddTicks(1010),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 7,
                            Key = "email_hotro",
                            NgayCapNhat = new DateTime(2026, 6, 11, 22, 32, 15, 284, DateTimeKind.Local).AddTicks(1011),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 8,
                            Key = "zalo",
                            NgayCapNhat = new DateTime(2026, 6, 11, 22, 32, 15, 284, DateTimeKind.Local).AddTicks(1012),
                            Trangthai = true
                        });
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.TienNghi", b =>
                {
                    b.Property<int>("MaTienNghi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTienNghi"));

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTienNghi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTienNghi");

                    b.ToTable("TienNghi");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.Tour", b =>
                {
                    b.Property<int>("MaTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTour"));

                    b.Property<string>("DiemKhoiHanh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LuotDat")
                        .HasColumnType("int");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiTour")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenTour")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ThoiGianTour")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaTour");

                    b.HasIndex("MaLoaiTour");

                    b.ToTable("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.Tour_KhachSan", b =>
                {
                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachSan")
                        .HasColumnType("int");

                    b.Property<int>("KhachSanMaKhachSan")
                        .HasColumnType("int");

                    b.Property<int>("TourMaTour")
                        .HasColumnType("int");

                    b.HasKey("MaTour", "MaKhachSan");

                    b.HasIndex("KhachSanMaKhachSan");

                    b.HasIndex("TourMaTour");

                    b.ToTable("Tour_KhachSan");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.UuDai", b =>
                {
                    b.Property<int>("MaUuDai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaUuDai"));

                    b.Property<decimal>("DieuKienApDung")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<float>("PhanTramGiam")
                        .HasColumnType("real");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenUuDai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaUuDai");

                    b.ToTable("UuDai");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro");

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            TenVaiTro = "Quản Trị Viên"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            TenVaiTro = "Nhân Viên"
                        },
                        new
                        {
                            MaVaiTro = 3,
                            TenVaiTro = "Hướng Dẫn Viên"
                        },
                        new
                        {
                            MaVaiTro = 4,
                            TenVaiTro = "Khách Hàng"
                        });
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.CTLichTrinh", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.DiaDiem", "DiaDiem")
                        .WithMany("CTLichTrinhs")
                        .HasForeignKey("MaDiaDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.LichTrinh", "LichTrinh")
                        .WithMany("CTLichTrinhs")
                        .HasForeignKey("MaLichTrinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaDiem");

                    b.Navigation("LichTrinh");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.ChuyenKhoiHanh", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "HuongDanVien")
                        .WithMany("ChuyenKhoiHanhs")
                        .HasForeignKey("MaHDV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.PhuongTien", "PhuongTien")
                        .WithMany("ChuyenKhoiHanhs")
                        .HasForeignKey("MaPhuongTien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.Tour", "Tour")
                        .WithMany("ChuyenKhoiHanhs")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HuongDanVien");

                    b.Navigation("PhuongTien");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DanhGia", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.Tour", "Tour")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DanhSachYeuThich", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhSachYeuThichs")
                        .HasForeignKey("NguoiDungMaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.Tour", "Tour")
                        .WithMany("DanhSachYeuThichs")
                        .HasForeignKey("TourMaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DonDatTour", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.ChuyenKhoiHanh", "ChuyenKhoiHanh")
                        .WithMany("DonDatTours")
                        .HasForeignKey("MaChuyen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.KhachSan", "KhachSan")
                        .WithMany("DonDatTours")
                        .HasForeignKey("MaKhachSan");

                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany("DonDatTours")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.UuDai", "UuDai")
                        .WithMany("DonDatTours")
                        .HasForeignKey("MaUuDai");

                    b.Navigation("ChuyenKhoiHanh");

                    b.Navigation("KhachSan");

                    b.Navigation("NguoiDung");

                    b.Navigation("UuDai");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.GiaChuyen", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.ChuyenKhoiHanh", "ChuyenKhoiHanh")
                        .WithMany("GiaChuyens")
                        .HasForeignKey("Machuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenKhoiHanh");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.HinhAnhSK", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.KhachSan", "KhachSan")
                        .WithMany("HinhAnhSKs")
                        .HasForeignKey("MaKhachSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.HinhAnhTour", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.Tour", "Tour")
                        .WithMany("HinhAnhTours")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.KS_TN", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.KhachSan", "KhachSan")
                        .WithMany("KS_TNs")
                        .HasForeignKey("KhachSanMaKhachSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.TienNghi", "TienNghi")
                        .WithMany("KS_TNs")
                        .HasForeignKey("TienNghiMaTienNghi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");

                    b.Navigation("TienNghi");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.KhachHang", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.DonDatTour", "DonDatTour")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaDonDatTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatTour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.LichTrinh", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.Tour", "Tour")
                        .WithMany("LichTrinhs")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.NguoiDung", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.PhienDangNhap", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany("PhienDangNhaps")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.SoThichNguoiDung", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.CLoaiHinhTour", "LoaiHinhTour")
                        .WithMany("SoThichNguoiDungs")
                        .HasForeignKey("LoaiHinhTourMaLoaiTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany("SoThichNguoiDungs")
                        .HasForeignKey("NguoiDungMaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHinhTour");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.ThanhToan", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.DonDatTour", "DonDatTour")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDonDatTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatTour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.Tour", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.CLoaiHinhTour", "LoaiHinhTour")
                        .WithMany("Tours")
                        .HasForeignKey("MaLoaiTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHinhTour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.Tour_KhachSan", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.KhachSan", "KhachSan")
                        .WithMany("Tour_KhachSans")
                        .HasForeignKey("KhachSanMaKhachSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.Tour", "Tour")
                        .WithMany("Tour_KhachSans")
                        .HasForeignKey("TourMaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.CLoaiHinhTour", b =>
                {
                    b.Navigation("SoThichNguoiDungs");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.ChuyenKhoiHanh", b =>
                {
                    b.Navigation("DonDatTours");

                    b.Navigation("GiaChuyens");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DiaDiem", b =>
                {
                    b.Navigation("CTLichTrinhs");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DonDatTour", b =>
                {
                    b.Navigation("KhachHangs");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.KhachSan", b =>
                {
                    b.Navigation("DonDatTours");

                    b.Navigation("HinhAnhSKs");

                    b.Navigation("KS_TNs");

                    b.Navigation("Tour_KhachSans");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.LichTrinh", b =>
                {
                    b.Navigation("CTLichTrinhs");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.NguoiDung", b =>
                {
                    b.Navigation("ChuyenKhoiHanhs");

                    b.Navigation("DanhGias");

                    b.Navigation("DanhSachYeuThichs");

                    b.Navigation("DonDatTours");

                    b.Navigation("PhienDangNhaps");

                    b.Navigation("SoThichNguoiDungs");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.PhuongTien", b =>
                {
                    b.Navigation("ChuyenKhoiHanhs");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.TienNghi", b =>
                {
                    b.Navigation("KS_TNs");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.Tour", b =>
                {
                    b.Navigation("ChuyenKhoiHanhs");

                    b.Navigation("DanhGias");

                    b.Navigation("DanhSachYeuThichs");

                    b.Navigation("HinhAnhTours");

                    b.Navigation("LichTrinhs");

                    b.Navigation("Tour_KhachSans");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.UuDai", b =>
                {
                    b.Navigation("DonDatTours");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
