// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using travel_recommendation_and_booking_system.Data;

#nullable disable

namespace travelrecommendationandbookingsystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoaiDiaDiem", b =>
                {
                    b.Property<int>("MaLoaiDiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiDiaDiem"));

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayxoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenLoaiDiaDiem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaLoaiDiaDiem");

                    b.ToTable("LoaiDiaDiem");
                });

            modelBuilder.Entity("ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<string>("LinkChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiThongBao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaThongBao");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("ThongBaoNguoiNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("MaThongBao")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDoc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaThongBao");

                    b.ToTable("ThongBaoNguoiNhan");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.Banner", b =>
                {
                    b.Property<int>("MaBanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBanner"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LinkLienKet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaBanner");

                    b.ToTable("Banner");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.CLoaiHinhTour", b =>
                {
                    b.Property<int>("MaLoaiTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiTour"));

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiTour")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLoaiTour");

                    b.ToTable("LoaiHinhTour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.CTLichTrinh", b =>
                {
                    b.Property<int>("MaCTLT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTLT"));

                    b.Property<string>("GioBatDau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioKetThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoatDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHoatDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaDiaDiem")
                        .HasColumnType("int");

                    b.Property<int>("MaLichTrinh")
                        .HasColumnType("int");

                    b.HasKey("MaCTLT");

                    b.HasIndex("MaDiaDiem");

                    b.HasIndex("MaLichTrinh");

                    b.ToTable("CTLichTrinh");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.ChuyenKhoiHanh", b =>
                {
                    b.Property<int>("MaChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuyen"));

                    b.Property<string>("DiemDen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiemKhoiHanh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GioDenNoiDi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GioDenNoiVe")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaChuyenCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaHDV")
                        .HasColumnType("int");

                    b.Property<int>("MaPhuongTien")
                        .HasColumnType("int");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKhoiHanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SoChoDaDat")
                        .HasColumnType("int");

                    b.Property<int>("SoChoToiDa")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaChuyen");

                    b.HasIndex("MaHDV");

                    b.HasIndex("MaPhuongTien");

                    b.HasIndex("MaTour");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("ChuyenKhoiHanh");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("DiemDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("GhiChuKiemDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTour");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DanhSachYeuThich", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung", "MaTour");

                    b.HasIndex("MaTour")
                        .HasDatabaseName("IX_DanhSachYeuThich_MaTour");

                    b.ToTable("DanhSachYeuThich");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DiaDiem", b =>
                {
                    b.Property<int>("MaDiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiaDiem"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LoaiDiaDiem")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TinhThanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDiaDiem");

                    b.HasIndex("LoaiDiaDiem");

                    b.ToTable("DiaDiem");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DonDatTour", b =>
                {
                    b.Property<int>("MaDonDatTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonDatTour"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("GiaEmBeTaiDat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaNguoiLonTaiDat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTreEmTaiDat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTriGiamTaiDat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnhHuy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaChuyen")
                        .HasColumnType("int");

                    b.Property<string>("MaDatCho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVienDuyet")
                        .HasColumnType("int");

                    b.Property<int?>("MaUuDai")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhuThuPhongDonTaiDat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SoEmBe")
                        .HasColumnType("int");

                    b.Property<int>("SoNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SoPhongDon")
                        .HasColumnType("int");

                    b.Property<int>("SoTreEm")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThaiDon")
                        .HasColumnType("int");

                    b.HasKey("MaDonDatTour");

                    b.HasIndex("MaChuyen");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaNhanVienDuyet");

                    b.HasIndex("MaUuDai");

                    b.ToTable("DonDatTour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.GiaChuyen", b =>
                {
                    b.Property<int>("MaGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGia"));

                    b.Property<decimal>("GiaEmBe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaNguoiLon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTreEm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Machuyen")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhuThuPhongDon")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaGia");

                    b.HasIndex("Machuyen");

                    b.ToTable("GiaChuyen");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.GiuCho", b =>
                {
                    b.Property<int>("MaGiuCho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiuCho"));

                    b.Property<int>("MaChuyen")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoChoGiu")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianHetHan")
                        .HasColumnType("datetime2");

                    b.HasKey("MaGiuCho");

                    b.HasIndex("MaChuyen");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("GiuCho");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.HinhAnhSK", b =>
                {
                    b.Property<int>("MaAnhSK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnhSK"));

                    b.Property<bool>("AnhChinh")
                        .HasColumnType("bit");

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaKhachSan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaAnhSK");

                    b.HasIndex("MaKhachSan");

                    b.ToTable("HinhAnhSK");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.HinhAnhTour", b =>
                {
                    b.Property<int>("MaAnhTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnhTour"));

                    b.Property<bool>("AnhChinh")
                        .HasColumnType("bit");

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaAnhTour");

                    b.HasIndex("MaTour");

                    b.ToTable("HinhAnhTour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.KS_TI", b =>
                {
                    b.Property<int>("MaKhachSan")
                        .HasColumnType("int");

                    b.Property<int>("MaTienIch")
                        .HasColumnType("int");

                    b.HasKey("MaKhachSan", "MaTienIch");

                    b.HasIndex("MaTienIch")
                        .HasDatabaseName("IX_KS_TN_MaTienIch");

                    b.ToTable("KS_TI");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LoaiKhach")
                        .HasColumnType("int");

                    b.Property<int>("MaDonDatTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PhongDon")
                        .HasColumnType("bit");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaDonDatTour");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.KhachSan", b =>
                {
                    b.Property<int>("MaKhachSan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachSan"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.Property<string>("TenKhachSan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaKhachSan");

                    b.ToTable("KhachSan");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.LichTrinh", b =>
                {
                    b.Property<int>("MaLichTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichTrinh"));

                    b.Property<string>("BuaAn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LuuY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaKhachSan")
                        .HasColumnType("int");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoThuTuNgay")
                        .HasColumnType("int");

                    b.Property<string>("TenLichTrinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLichTrinh");

                    b.HasIndex("MaKhachSan");

                    b.HasIndex("MaTour");

                    b.ToTable("LichTrinh");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.LienHe", b =>
                {
                    b.Property<int>("MaLienHe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLienHe"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLienHe");

                    b.ToTable("LienHe");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.Newsletter", b =>
                {
                    b.Property<int>("MaNewsletter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNewsletter"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNewsletter");

                    b.ToTable("Newsletter");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DuongDanAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LanGuiOtpGanNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LanNhapSaiOtpGanNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SoLanNhapSaiOtp")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianHetHanOtp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DuongDanAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            MaNhanVien = 1,
                            Cccd = "098765432112",
                            Email = "admin@gmail.com",
                            GioiTinh = false,
                            HoTen = "Quản Trị Viên",
                            MaVaiTro = 1,
                            MatKhau = "$2a$11$sDJWOtDyw6ozpEVQGP9m2.0..NfQji8JmZOBy/A6g/lncXvDPyuZO",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(727),
                            NgayTao = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(698),
                            SoDienThoai = "0988888888",
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.NhatKyHeThong", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("DiaChiIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaTriSau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaTriTruoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaDoiTuong")
                        .HasColumnType("int");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("TenBangTacDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrinhDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhatKy");

                    b.ToTable("NhatKyHeThong");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.PaymentPayload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DanhSachHanhKhachJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaChuyen")
                        .HasColumnType("int");

                    b.Property<int>("MaGiuCho")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaUuDai")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDauThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoEmBe")
                        .HasColumnType("int");

                    b.Property<int>("SoNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SoTreEm")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTienGoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TxnRef")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PaymentPayload");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.PhienDangNhap", b =>
                {
                    b.Property<int>("MaPhien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhien"));

                    b.Property<string>("DiaChiIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaPhien");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PhienDangNhaps");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.PhuongTien", b =>
                {
                    b.Property<int>("MaPhuongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuongTien"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaVietTat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenPhuongTien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaPhuongTien");

                    b.ToTable("PhuongTien");

                    b.HasData(
                        new
                        {
                            MaPhuongTien = 1,
                            Icon = "Plane",
                            MaVietTat = "MB",
                            NgayCapNhat = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenPhuongTien = "Máy Bay",
                            TrangThai = true
                        },
                        new
                        {
                            MaPhuongTien = 2,
                            Icon = "Bus",
                            MaVietTat = "OT",
                            NgayCapNhat = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenPhuongTien = "Ô Tô",
                            TrangThai = true
                        },
                        new
                        {
                            MaPhuongTien = 3,
                            Icon = "Train",
                            MaVietTat = "TH",
                            NgayCapNhat = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenPhuongTien = "Tàu Hỏa",
                            TrangThai = true
                        },
                        new
                        {
                            MaPhuongTien = 4,
                            Icon = "Ship",
                            MaVietTat = "TT",
                            NgayCapNhat = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenPhuongTien = "Tàu Thủy",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.SoThichDiaDiemNguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaDiaDiem")
                        .HasColumnType("int");

                    b.Property<float>("DiemYeuThich")
                        .HasColumnType("real");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNguoiDung", "MaDiaDiem");

                    b.HasIndex("MaDiaDiem");

                    b.ToTable("SoThichDiaDiemNguoiDungs");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.SoThichNguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiTour")
                        .HasColumnType("int");

                    b.Property<float>("DiemYeuThich")
                        .HasColumnType("real");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNguoiDung", "MaLoaiTour");

                    b.HasIndex("MaLoaiTour");

                    b.ToTable("SoThichNguoiDung");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<int>("MaDonDatTour")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaNhanVienXuLyHoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayHoanTien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PhuongThucThanhToan")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTienHoan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThaiThanhToan")
                        .HasColumnType("int");

                    b.Property<string>("VnpTransactionNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDonDatTour");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.ThongTinTrang", b =>
                {
                    b.Property<int>("MaTTTrang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTTTrang"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Noidung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("MaTTTrang");

                    b.ToTable("ThongTinTrang");

                    b.HasData(
                        new
                        {
                            MaTTTrang = 1,
                            Key = "logo_url",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1607),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 2,
                            Key = "ten_trang",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1615),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 3,
                            Key = "facebook_url",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1616),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 4,
                            Key = "dia_chi",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1617),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 5,
                            Key = "so_dien_thoai",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1618),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 7,
                            Key = "email_hotro",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1619),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 8,
                            Key = "zalo",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1620),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 9,
                            Key = "faq_1_question",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1621),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 10,
                            Key = "faq_1_answer",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1623),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 11,
                            Key = "faq_2_question",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1743),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 12,
                            Key = "faq_2_answer",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1744),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 13,
                            Key = "faq_3_question",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1746),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 14,
                            Key = "faq_3_answer",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1747),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 15,
                            Key = "faq_4_question",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1748),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 16,
                            Key = "faq_4_answer",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1749),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 17,
                            Key = "faq_5_question",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1750),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 18,
                            Key = "faq_5_answer",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1751),
                            Trangthai = true
                        },
                        new
                        {
                            MaTTTrang = 19,
                            Key = "Map_Trang_Lien_He",
                            NgayCapNhat = new DateTime(2026, 7, 10, 10, 2, 16, 487, DateTimeKind.Local).AddTicks(1765),
                            Trangthai = true
                        });
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.TienIch", b =>
                {
                    b.Property<int>("MaTienIch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTienIch"));

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTienIch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTienIch");

                    b.ToTable("TienIch");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.Tour", b =>
                {
                    b.Property<int>("MaTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTour"));

                    b.Property<int>("Dem")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaTu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LuotDat")
                        .HasColumnType("int");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiTour")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ngay")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTour")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaTour");

                    b.HasIndex("MaLoaiTour");

                    b.ToTable("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.TourRecommendationScore", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.HasKey("MaNguoiDung", "MaTour");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTour");

                    b.ToTable("TourRecommendationScore");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.Tour_KhachSan", b =>
                {
                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachSan")
                        .HasColumnType("int");

                    b.Property<int>("MaTourKhachSan")
                        .HasColumnType("int");

                    b.HasKey("MaTour", "MaKhachSan");

                    b.HasIndex("MaKhachSan")
                        .HasDatabaseName("IX_Tour_KhachSan_MaKhachSan");

                    b.ToTable("Tour_KhachSan");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.TrangThaiTuongTac", b =>
                {
                    b.Property<int>("MaTuongTac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTuongTac"));

                    b.Property<bool>("DaQuanTamLau")
                        .HasColumnType("bit");

                    b.Property<bool>("DaXemChiTiet")
                        .HasColumnType("bit");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.HasKey("MaTuongTac");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaTour");

                    b.ToTable("TrangThaiTuongTac");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.UuDai", b =>
                {
                    b.Property<int>("MaUuDai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaUuDai"));

                    b.Property<decimal>("DieuKienApDung")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhanTramGiam")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SoLuongDaDung")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenUuDai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaUuDai");

                    b.ToTable("UuDai");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro");

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            TenVaiTro = "Quản Trị Viên"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            TenVaiTro = "Nhân Viên"
                        },
                        new
                        {
                            MaVaiTro = 3,
                            TenVaiTro = "Hướng Dẫn Viên"
                        },
                        new
                        {
                            MaVaiTro = 4,
                            TenVaiTro = "Khách Hàng"
                        });
                });

            modelBuilder.Entity("ThongBaoNguoiNhan", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongBaoNguoiNhans")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("travel_recommendation_and_booking_system.Models.NhanVien", "NhanVien")
                        .WithMany("ThongBaoNguoiNhans")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThongBao", "ThongBao")
                        .WithMany("NguoiNhans")
                        .HasForeignKey("MaThongBao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("NhanVien");

                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.CTLichTrinh", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.DiaDiem", "DiaDiem")
                        .WithMany("CTLichTrinhs")
                        .HasForeignKey("MaDiaDiem");

                    b.HasOne("travel_recommendation_and_booking_system.Models.LichTrinh", "LichTrinh")
                        .WithMany("CTLichTrinhs")
                        .HasForeignKey("MaLichTrinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaDiem");

                    b.Navigation("LichTrinh");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.ChuyenKhoiHanh", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaHDV");

                    b.HasOne("travel_recommendation_and_booking_system.Models.PhuongTien", "PhuongTien")
                        .WithMany("ChuyenKhoiHanhs")
                        .HasForeignKey("MaPhuongTien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.Tour", "Tour")
                        .WithMany("ChuyenKhoiHanhs")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", null)
                        .WithMany("ChuyenKhoiHanhs")
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.Navigation("NhanVien");

                    b.Navigation("PhuongTien");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DanhGia", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.Tour", "Tour")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DanhSachYeuThich", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhSachYeuThichs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.Tour", "Tour")
                        .WithMany("DanhSachYeuThichs")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DiaDiem", b =>
                {
                    b.HasOne("LoaiDiaDiem", "LoaiDiaDiemNavigation")
                        .WithMany("DanhSachDiaDiem")
                        .HasForeignKey("LoaiDiaDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiDiaDiemNavigation");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DonDatTour", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.ChuyenKhoiHanh", "ChuyenKhoiHanh")
                        .WithMany("DonDatTours")
                        .HasForeignKey("MaChuyen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany("DonDatTours")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVienDuyet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("travel_recommendation_and_booking_system.Models.UuDai", "UuDai")
                        .WithMany("DonDatTours")
                        .HasForeignKey("MaUuDai")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChuyenKhoiHanh");

                    b.Navigation("NguoiDung");

                    b.Navigation("NhanVien");

                    b.Navigation("UuDai");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.GiaChuyen", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.ChuyenKhoiHanh", "ChuyenKhoiHanh")
                        .WithMany("GiaChuyens")
                        .HasForeignKey("Machuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenKhoiHanh");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.GiuCho", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.ChuyenKhoiHanh", "ChuyenKhoiHanh")
                        .WithMany()
                        .HasForeignKey("MaChuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenKhoiHanh");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.HinhAnhSK", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.KhachSan", "KhachSan")
                        .WithMany("HinhAnhSKs")
                        .HasForeignKey("MaKhachSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.HinhAnhTour", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.Tour", "Tour")
                        .WithMany("HinhAnhTours")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.KS_TI", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.KhachSan", "KhachSan")
                        .WithMany("KS_TNs")
                        .HasForeignKey("MaKhachSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.TienIch", "TienIch")
                        .WithMany("KS_TNs")
                        .HasForeignKey("MaTienIch")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");

                    b.Navigation("TienIch");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.KhachHang", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.DonDatTour", "DonDatTour")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaDonDatTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatTour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.LichTrinh", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.KhachSan", "KhachSan")
                        .WithMany()
                        .HasForeignKey("MaKhachSan");

                    b.HasOne("travel_recommendation_and_booking_system.Models.Tour", "Tour")
                        .WithMany("LichTrinhs")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhachSan");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.NguoiDung", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.NhanVien", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.VaiTro", "VaiTro")
                        .WithMany()
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.PhienDangNhap", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany("PhienDangNhaps")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("travel_recommendation_and_booking_system.Models.NhanVien", "NhanVien")
                        .WithMany("PhienDangNhaps")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiDung");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.SoThichDiaDiemNguoiDung", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.DiaDiem", "DiaDiem")
                        .WithMany("SoThichDiaDiemNguoiDungs")
                        .HasForeignKey("MaDiaDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany("SoThichDiaDiemNguoiDungs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaDiem");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.SoThichNguoiDung", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.CLoaiHinhTour", "LoaiHinhTour")
                        .WithMany("SoThichNguoiDungs")
                        .HasForeignKey("MaLoaiTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany("SoThichNguoiDungs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHinhTour");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.ThanhToan", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.DonDatTour", "DonDatTour")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDonDatTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatTour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.Tour", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.CLoaiHinhTour", "LoaiHinhTour")
                        .WithMany("Tours")
                        .HasForeignKey("MaLoaiTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHinhTour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.TourRecommendationScore", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.Tour_KhachSan", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.KhachSan", "KhachSan")
                        .WithMany("Tour_KhachSans")
                        .HasForeignKey("MaKhachSan")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.Tour", "Tour")
                        .WithMany("Tour_KhachSans")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhachSan");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.TrangThaiTuongTac", b =>
                {
                    b.HasOne("travel_recommendation_and_booking_system.Models.NguoiDung", "NguoiDung")
                        .WithMany("TrangThaiTuongTacs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_recommendation_and_booking_system.Models.Tour", "Tour")
                        .WithMany("TrangThaiTuongTacs")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("LoaiDiaDiem", b =>
                {
                    b.Navigation("DanhSachDiaDiem");
                });

            modelBuilder.Entity("ThongBao", b =>
                {
                    b.Navigation("NguoiNhans");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.CLoaiHinhTour", b =>
                {
                    b.Navigation("SoThichNguoiDungs");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.ChuyenKhoiHanh", b =>
                {
                    b.Navigation("DonDatTours");

                    b.Navigation("GiaChuyens");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DiaDiem", b =>
                {
                    b.Navigation("CTLichTrinhs");

                    b.Navigation("SoThichDiaDiemNguoiDungs");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.DonDatTour", b =>
                {
                    b.Navigation("KhachHangs");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.KhachSan", b =>
                {
                    b.Navigation("HinhAnhSKs");

                    b.Navigation("KS_TNs");

                    b.Navigation("Tour_KhachSans");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.LichTrinh", b =>
                {
                    b.Navigation("CTLichTrinhs");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.NguoiDung", b =>
                {
                    b.Navigation("ChuyenKhoiHanhs");

                    b.Navigation("DanhGias");

                    b.Navigation("DanhSachYeuThichs");

                    b.Navigation("DonDatTours");

                    b.Navigation("PhienDangNhaps");

                    b.Navigation("SoThichDiaDiemNguoiDungs");

                    b.Navigation("SoThichNguoiDungs");

                    b.Navigation("ThongBaoNguoiNhans");

                    b.Navigation("TrangThaiTuongTacs");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.NhanVien", b =>
                {
                    b.Navigation("PhienDangNhaps");

                    b.Navigation("ThongBaoNguoiNhans");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.PhuongTien", b =>
                {
                    b.Navigation("ChuyenKhoiHanhs");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.TienIch", b =>
                {
                    b.Navigation("KS_TNs");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.Tour", b =>
                {
                    b.Navigation("ChuyenKhoiHanhs");

                    b.Navigation("DanhGias");

                    b.Navigation("DanhSachYeuThichs");

                    b.Navigation("HinhAnhTours");

                    b.Navigation("LichTrinhs");

                    b.Navigation("Tour_KhachSans");

                    b.Navigation("TrangThaiTuongTacs");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.UuDai", b =>
                {
                    b.Navigation("DonDatTours");
                });

            modelBuilder.Entity("travel_recommendation_and_booking_system.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
